version: '2'
services:
    financialtracking-app:
        image: financialtracking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://financialtracking-postgresql:5432/FinancialTracking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    financialtracking-postgresql:
        extends:
            file: postgresql.yml
            service: financialtracking-postgresql
